import logging

logger = logging.getLogger("agent-commerce-core.trust_metrics")


def calculate_hybrid_trust_score(
    llm_score: float, extraction_route: str, data_freshness_seconds: int | None = None
) -> float:
    """
    Calculates a deterministic hybrid trust score combining LLM self-evaluation
    with absolute infrastructure metrics (route stability, data freshness).

    Args:
        llm_score: Baseline confidence score generated by the LLM (0.0 - 1.0).
        extraction_route: 'jina', 'firecrawl', or 'search'.
        data_freshness_seconds: Age of the data in seconds, if applicable.

    Returns:
        float: The final clamped trust score (0.0 to 1.0).
    """
    score = float(llm_score)

    # 1. Extraction Route Penalty (Structural Stability)
    if extraction_route == "jina":
        pass  # Most stable, direct DOM parse
    elif extraction_route == "firecrawl":
        score -= 0.05  # Secondary scraper, slight chance of noise
    elif extraction_route == "search":
        score -= 0.15  # Search engine fallback, highest chance of fragmented context

    # 2. Data Freshness Penalty
    if data_freshness_seconds is not None:
        days_old = data_freshness_seconds / 86400
        if days_old > 30:
            score -= 0.15  # Stale data penalty
        elif days_old > 7:
            score -= 0.05  # Slight aging penalty

    # 3. Ensure Strict Bounds
    final_score = max(0.0, min(1.0, round(score, 2)))

    logger.info(
        f"Hybrid Trust Score Calculated: {final_score} "
        f"(LLM: {llm_score}, Route: {extraction_route}, Freshness: {data_freshness_seconds}s)"
    )

    return final_score
